// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { HunkLocation } from "./HunkLocation";
import type { MultilineString } from "./MultilineString";

export interface ChangeHunk {
    location: HunkLocation;
    lines: MultilineString;
}
