// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CommitId } from "./CommitId";
import type { RevId } from "./RevId";
import type { TreePath } from "./TreePath";

export interface CopyChanges {
    from_id: CommitId;
    to_id: RevId;
    paths: Array<TreePath>;
}
