// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RevId } from "./RevId";

export interface CopyChanges { from_change_id: RevId, to_change_id: RevId, }