// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CommitId } from "./CommitId";
import type { RevId } from "./RevId";

export interface CreateRevisionBetween { after_id: CommitId, before_id: RevId, }