// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RevId } from "./RevId";
import type { StoreRef } from "./StoreRef";

export interface CreateRef {
    id: RevId;
    ref: StoreRef;
}
