// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type DiffPath = { "type": "Added", relative_path: string, } | { "type": "Deleted", relative_path: string, } | { "type": "Modified", relative_path: string, };