// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FileRange } from "./FileRange";

export interface HunkLocation {
    from_file: FileRange;
    to_file: FileRange;
}
