// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Id } from "./Id";
import type { Text } from "./Text";

export interface LogChange { change_id: Id, commit_id: Id, description: Text, email: string, timestamp: string, }