// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LogEdge } from "./LogEdge";
import type { RevHeader } from "./RevHeader";

export interface LogNode { revision: RevHeader, edges: Array<LogEdge>, }