// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LogLine } from "./LogLine";
import type { LogRow } from "./LogRow";

export interface LogPage { rows: Array<LogRow>, lines: Array<LogLine>, has_more: boolean, }