// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LogCoordinates } from "./LogCoordinates";
import type { LogLine } from "./LogLine";
import type { RevHeader } from "./RevHeader";

export interface LogRow { revision: RevHeader, location: LogCoordinates, padding: number, lines: Array<LogLine>, }