// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LogCoordinates } from "./LogCoordinates";
import type { RevHeader } from "./RevHeader";

export interface LogRow { location: LogCoordinates, padding: number, revision: RevHeader, }