// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RevId } from "./RevId";
import type { StoreRef } from "./StoreRef";

export interface MoveRef {
    ref: StoreRef;
    to_id: RevId;
}
