// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RefName } from "./RefName";
import type { RevId } from "./RevId";

export interface MoveBranch { name: RefName, to_id: RevId, }