// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RevId } from "./RevId";

export interface MoveSource { change_id: RevId, parent_ids: Array<RevId>, }