// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ChangeHunk } from "./ChangeHunk";
import type { CommitId } from "./CommitId";
import type { RevId } from "./RevId";
import type { TreePath } from "./TreePath";

export interface MoveHunk { from_id: RevId, to_id: CommitId, path: TreePath, hunk: ChangeHunk, }