// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RepoStatus } from "./RepoStatus";

export type MutationResult = { "type": "Unchanged" } | { "type": "Updated", new_status: RepoStatus, } | { "type": "Failed", message: string, };