// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DisplayPath } from "./DisplayPath";
import type { RepoStatus } from "./RepoStatus";

export interface RepoConfig { absolute_path: DisplayPath, default_revset: string, status: RepoStatus, }