// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CommitId } from "./CommitId";

export interface RepoStatus { operation_description: string, working_copy: CommitId, }