// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ChangeHunk } from "./ChangeHunk";
import type { TreePath } from "./TreePath";

export interface RevConflict {
    path: TreePath;
    hunk: ChangeHunk;
}
