// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MultilineString } from "./MultilineString";
import type { TreePath } from "./TreePath";

export interface RevConflict { path: TreePath, hunk: MultilineString, }