// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DiffPath } from "./DiffPath";
import type { RevHeader } from "./RevHeader";

export interface RevDetail { header: RevHeader, parents: Array<RevHeader>, diff: Array<DiffPath>, }