// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MultilineString } from "./MultilineString";
import type { RefName } from "./RefName";
import type { RevAuthor } from "./RevAuthor";
import type { RevId } from "./RevId";

export interface RevHeader { change_id: RevId, commit_id: RevId, description: MultilineString, author: RevAuthor, has_conflict: boolean, is_working_copy: boolean, is_immutable: boolean, branches: Array<RefName>, parents: number, }