// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CommitId } from "./CommitId";
import type { MultilineString } from "./MultilineString";
import type { RevAuthor } from "./RevAuthor";
import type { RevId } from "./RevId";
import type { StoreRef } from "./StoreRef";

export interface RevHeader {
    id: RevId;
    description: MultilineString;
    author: RevAuthor;
    has_conflict: boolean;
    is_working_copy: boolean;
    is_immutable: boolean;
    refs: Array<StoreRef>;
    parent_ids: Array<CommitId>;
}
