// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MultilineString } from "./MultilineString";
import type { RevId } from "./RevId";

export interface RevHeader { change_id: RevId, commit_id: RevId, description: MultilineString, author: string, email: string, timestamp: string, has_conflict: boolean, }