// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DisplayPath } from "./DisplayPath";

export interface TreePath {
    repo_path: string;
    relative_path: DisplayPath;
}
