// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DisplayPath } from "./DisplayPath";

export type TreePath = { "type": "Added", relative_path: DisplayPath, } | { "type": "Deleted", relative_path: DisplayPath, } | { "type": "Modified", relative_path: DisplayPath, };