// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ChangeRange } from "./ChangeRange";

export interface ChangeLocation { from_file: ChangeRange, to_file: ChangeRange, }