// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ChangeLocation } from "./ChangeLocation";
import type { MultilineString } from "./MultilineString";

export interface ChangeHunk { location: ChangeLocation, lines: MultilineString, }