// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CommitId } from "./CommitId";
import type { RevSet } from "./RevSet";
import type { TreePath } from "./TreePath";

export interface CopyChanges { from_id: CommitId, to_set: RevSet, paths: Array<TreePath>, }