// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RevId } from "./RevId";

export interface DescribeRevision { id: RevId, new_description: string, reset_author: boolean, }