// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RevId } from "./RevId";
import type { TreePath } from "./TreePath";

export interface ExternalResolve { id: RevId, path: TreePath, }