// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { StoreRef } from "./StoreRef";

export type GitFetch = { "type": "AllBookmarks", remote_name: string, } | { "type": "AllRemotes", branch_ref: StoreRef, } | { "type": "RemoteBookmark", remote_name: string, branch_ref: StoreRef, };