// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { GitRefspec } from "./GitRefspec";
import type { InputResponse } from "./InputResponse";

export interface GitPush { refspec: GitRefspec, input: InputResponse | null, }