// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RevId } from "./RevId";
import type { RevSet } from "./RevSet";

export interface InsertRevisions { set: RevSet, after_id: RevId, before_id: RevId, }