// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RevId } from "./RevId";
import type { RevSet } from "./RevSet";

export interface MoveRevisions { set: RevSet, parent_ids: Array<RevId>, }