// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CommitId } from "./CommitId";
import type { RevSet } from "./RevSet";
import type { TreePath } from "./TreePath";

export interface MoveChanges { from: RevSet, to_id: CommitId, paths: Array<TreePath>, }