// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CommitId } from "./CommitId";
import type { RevId } from "./RevId";

export interface MoveSource { id: RevId, parent_ids: Array<CommitId>, }