// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface OpLogEntry { id: string, description: string, timestamp: string, tags: Record<string, string>, is_head: boolean, }