// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { OpLogEntry } from "./OpLogEntry";

export interface OpLog { entries: Array<OpLogEntry>, }