// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ProgressEvent = { "type": "Progress", overall_percent: number, bytes_downloaded: bigint | null, } | { "type": "Message", text: string, };