// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type RepoEvent = { "type": "CloneURL" } | { "type": "CloneConfirm", url: string, path: string, } | { "type": "InitConfirm", path: string, has_git: boolean, };