// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ChangeHunk } from "./ChangeHunk";
import type { ChangeKind } from "./ChangeKind";
import type { TreePath } from "./TreePath";

export interface RevChange { kind: ChangeKind, path: TreePath, has_conflict: boolean, hunks: Array<ChangeHunk>, }