// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ChangeId } from "./ChangeId";
import type { CommitId } from "./CommitId";

export interface RevId { change: ChangeId, commit: CommitId, }