// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RevChange } from "./RevChange";
import type { RevConflict } from "./RevConflict";
import type { RevHeader } from "./RevHeader";
import type { RevSet } from "./RevSet";

export type RevsResult = { "type": "NotFound", set: RevSet, } | { "type": "Detail", set: RevSet, headers: Array<RevHeader>, parents: Array<RevHeader>, changes: Array<RevChange>, conflicts: Array<RevConflict>, };